kind: pipeline
name: default

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: v7lin/centos_systemctl
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    tags:
    - latest
